import Head from 'next/head'
import Image from 'next/image'
import logo from '../../../public/logo.png'
import logoOwp from '../../../public/owpLogo.png'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import EcommerceMainCard from '../../components/ecommerce/EcommerceMainCard'
import LoyaltyMainCard from '../../components/loyalty/LoyaltyMainCard'
import { useDispatch, useSelector } from 'react-redux';
import React, {useState, useEffect } from 'react';
import { setUser } from '../../slices/userSlice';
import { AppDispatch, RootState } from '@/store'
import { fetchUserData } from '@/slices/userActions'
import Millionare from '../../components/millionare'
import SweatContent from '@/components/sweat/SweatContent'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const dispatch = useDispatch<AppDispatch>()
  
  const user = useSelector((state: RootState) => state.user.user); // Annotate RootState
  const loading = useSelector((state: RootState) => state.user.loading);
  const error = useSelector((state: RootState) => state.user.error);
  const {fetchSweatData} = require('../api/sweatApi/index');
  const [token, setToken] = useState('');
  const [accessToken, setAccessToken] = useState('');
  const [sweatData, setSweatData] = useState('');

  useEffect(() => {
    // Check if we're in the browser environment before accessing localStorage
    if (typeof window !== 'undefined') {
      const storedToken = window.localStorage.getItem('email');
      const accessTokenLs = window.localStorage.getItem('access_token');      
      if (storedToken) {
        setToken(storedToken);
        setAccessToken(accessTokenLs)
      }
    }
  }, []); // Run this effect only once when the component mounts
  
  useEffect(() => {
    // Fetch user data when the component mounts
    dispatch(fetchUserData());
    const fetchData = async () => {
      try {
        const data = await fetchSweatData(fetchSweatData, accessToken);
        setSweatData(data)
        // Handle the API response as needed
      } catch (error) {
        console.error('Error:', error);
      }
    };
    fetchData()
  }, [dispatch, accessToken]);
console.log('sweatData', sweatData)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>{user?.email} {user?.name} {error} {loading}</h1> */}

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            DASHBOARD&nbsp;
            <code className={styles.code}>{token}</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src={logoOwp}
                alt="Vercel Logo"
                className={styles.vercelLogo}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src={logo}
            alt="OWPC Loyalty Logo"
            // width={180}
            // height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <span>
            <LoyaltyMainCard />
          </span>

          <span>
            <Millionare />
          </span>

          <span>
            <SweatContent sweatData={sweatData}/>
          </span>

          <span>
            <EcommerceMainCard />
          </span>
        </div>
      </main>
    </>
  )
}
