import Head from 'next/head'
import Image from 'next/image'
import logo from '../../../public/owpLogo.png'
import logoOwp from '../../../public/owpLogo.png'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useDispatch, useSelector } from 'react-redux';
import React, {useState, useEffect } from 'react';
import { AppDispatch, RootState } from '@/store'
import { fetchUserData } from '@/slices/userActions'
import SideNav from '@/components/SideNav'
import TopNav from '@/components/TopNav'
import OwpmContent from '@/components/millionare/OwpmContent'
import { useRouter } from 'next/router'
import SweatContent from '../sweatPage/index'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const dispatch = useDispatch<AppDispatch>()
  const router = useRouter();
  const user = useSelector((state: RootState) => state.user.user); // Annotate RootState
  const loading = useSelector((state: RootState) => state.user.loading);
  const error = useSelector((state: RootState) => state.user.error);
  // const fetchApiData = require('../api/sweatApi/index');

  // const isLinkActive = (path: string) => {
  //   return router.pathname === path ? 'active' : '';
  // };
  // const [sweatData, setSweatData] = useState('');
  // const [accessToken, setAccessToken] = useState('');
  // const [token, setToken] = useState('');


  // useEffect(() => {
  //   // Check if we're in the browser environment before accessing localStorage
  //   if (typeof window !== 'undefined') {
  //     const storedToken = window.localStorage.getItem('email');
  //     const accessTokenLs = window.localStorage.getItem('access_token');      
  //     if (storedToken) {
  //       setToken(storedToken);
  //       setAccessToken(accessTokenLs)
  //     }
  //   }
  // }, []); // Run this effect only once when the component mounts

  useEffect(() => {
    dispatch(fetchUserData());
  }, [dispatch]);




  const mainContent = () => {
    if (router.pathname === '/owpm') {
      return (
        <>
        <OwpmContent />
        </>
      );
    } 
    
    else if (router.pathname === '/sweatPage') {
      return (
        <>
        <SweatContent />   
        </>     
      );
    } 
    
    else {
      return null; // Default to no content for other routes
    }
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<TopNav />

<div className="container-fluid mt-3">
  <div className="row">
    <div className="col-sm-2">
        <SideNav />
    </div>

    <div className="col-sm-10">
      {mainContent()}
        {/* <OwpmContent /> */}
    </div>

  </div>
</div>

      
    </>
  )
}
