import Head from 'next/head'
import Image from 'next/image'
import logo from '../../../public/owpLogo.png'
import logoOwp from '../../../public/owpLogo.png'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useDispatch, useSelector } from 'react-redux';
import React, { useEffect } from 'react';
import { AppDispatch, RootState } from '@/store'
import { fetchUserData } from '@/slices/userActions'
import SideNav from '@/components/SideNav'
import TopNav from '@/components/TopNav'
import YearlyDraw from '@/components/millionare/yearlyDraw'

const inter = Inter({ subsets: ['latin'] })


export default function yearlyDraw() {
  const dispatch = useDispatch<AppDispatch>()
  
  const user = useSelector((state: RootState) => state.user.user); // Annotate RootState
  const loading = useSelector((state: RootState) => state.user.loading);
  const error = useSelector((state: RootState) => state.user.error);

  useEffect(() => {
    dispatch(fetchUserData());
  }, [dispatch]);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<TopNav />

<div className="container-fluid mt-3">
  <div className="row">
    <div className="col-sm-2">
        <SideNav />
    </div>

    <div className="col-sm-10">
        <YearlyDraw />
    </div>

  </div>
</div>

      
    </>
  )
}
